version: '3.1'

services:
  mariadb:
      image: mariadb:latest
      environment:
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=password
          - MYSQL_DATABASE=commit
          - MYSQL_RANDOM_ROOT_PASSWORD=yes
  kanopy:
      build: .
      depends_on:
        - mariadb
      volumes:
        - ./:/kanopy
      working_dir: /kanopy
      ports:
        - 8080:80

